services:
  derp-aio:
    image: xubiaolin/derp-aio:latest
    env_file:
      - .env
    container_name: derp-aio
    hostname: derp.${DERP_DOMAIN}
    ports:
      - ${DERP_ADDR}:${DERP_ADDR}
      - ${DERP_STUN_PORT}:${DERP_STUN_PORT}
      - ${DERP_STUN_PORT}:${DERP_STUN_PORT}/udp
    volumes:
      - /dev/net/tun:/dev/net/tun
      - ./ts_data:/var/lib/tailscale
      - ./log/derper:/var/log/derper
      - ./log/tailscaled:/var/log/tailscaled
      - ${CERT_PATH}/${DERP_DOMAIN}.key:/app/certs/${DERP_DOMAIN}.key
      - ${CERT_PATH}/${DERP_DOMAIN}.crt:/app/certs/${DERP_DOMAIN}.crt
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    restart: unless-stopped
