services:
  derp-aio:
    image: derp-aio
    container_name: derp-aio
    volumes:
      - /dev/net/tun:/dev/net/tun
      - ./ts_data:/var/lib/tailscale
      - ./log/derper:/var/log/derper
      - ./log/tailscaled:/var/log/tailscaled
      - /path/to/your-domain.com.key:/app/certs/your-domain.com.key
      - /path/to/your-domain.com.crt:/app/certs/your-domain.com.crt
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    environment:
      - DERP_DOMAIN=derp.markxu.vip
      - DERP_ADDR=:18443
      - DERP_STUN_PORT=19443
    restart: unless-stopped
